name = "Dracula"
background = "#282a36"
foreground = "#f8f8f2"
cursor     = "#bbbbbb"
selection  = "#44475a"

[ansi]
black          = "#000000"
red            = "#ff5555"
green          = "#50fa7b"
yellow         = "#f1fa8c"
blue           = "#bd93f9"
magenta        = "#ff79c6"
cyan           = "#8be9fd"
white          = "#bbbbbb"
bright_black   = "#555555"
bright_red     = "#ff5555"
bright_green   = "#50fa7b"
bright_yellow  = "#f1fa8c"
bright_blue    = "#caa9fa"
bright_magenta = "#ff79c6"
bright_cyan    = "#8be9fd"
bright_white   = "#ffffff"
