name = "Light"
background = "#ffffff"
foreground = "#333333"
cursor     = "#000000"
selection  = "#add6ff"

[ansi]
black          = "#000000"
red            = "#cd3131"
green          = "#00bc00"
yellow         = "#949800"
blue           = "#0451a5"
magenta        = "#bc05bc"
cyan           = "#0598bc"
white          = "#555555"
bright_black   = "#666666"
bright_red     = "#cd3131"
bright_green   = "#14ce14"
bright_yellow  = "#b5ba00"
bright_blue    = "#0451a5"
bright_magenta = "#bc05bc"
bright_cyan    = "#0598bc"
bright_white   = "#a5a5a5"
